version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew clean build

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/reports/tests/test
          destination: test_result

      - store_artifacts:
          path: build/reports/jacoco
          destination: test_coverage

      - store_artifacts:
          path: build/reports/pmd
          destination: pmd

      - store_artifacts:
          path: build/reports/checkstyle
          destination: checkstyle
